### ISSUE TITLE
NoSuchFileException

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#66]
V0.0.10

windows 10 home.

This issue occurs when i delete the files in the sync folder while its uploading them.

```
Creating cloud directory Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/constants/...
    0%               0/0 bytes
  100%               1/1 bytes
  done.
Creating cloud directory Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/containers/...
    0%               0/0 bytes
  100%               1/1 bytes
  done.
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/index.js...
    0%               0/0 bytes
  100%             564/564 bytes
  done.
Creating cloud directory Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/reducers/...
    0%               0/0 bytes
  100%               1/1 bytes
3 seconds after the last file event
java.nio.file.NoSuchFileException: C:\Users\meije\Goobox\Sia-UI-v1.3.0-win32-x64\resources\app\plugins\Terminal\js\reducers
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.nio.file.Files.getLastModifiedTime(Unknown Source)
        at io.goobox.sync.storj.db.SyncFile.setLocalData(SyncFile.java:115)
        at io.goobox.sync.storj.db.DB.setSynced(DB.java:141)
        at io.goobox.sync.storj.CreateCloudDirTask$1$1.onFilesReceived(CreateCloudDirTask.java:82)
        at io.storj.libstorj.Storj._listFiles(Native Method)
        at io.storj.libstorj.Storj.listFiles(Storj.java:166)
        at io.goobox.sync.storj.CreateCloudDirTask$1.onComplete(CreateCloudDirTask.java:70)
        at io.storj.libstorj.Storj._uploadFile(Native Method)
        at io.storj.libstorj.Storj.uploadFile(Storj.java:187)
        at io.goobox.sync.storj.CreateCloudDirTask.run(CreateCloudDirTask.java:54)
        at io.goobox.sync.storj.TaskExecutor.run(TaskExecutor.java:33)
  done.
Creating cloud directory Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/utils...
    0%               0/0 bytes
```

**Comment by MeijeSibbel** [comment]
There are no more files in the sync folder but it continues to try and upload it.
 
```
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/utils/helpers.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/reducers/commandline.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/reducers/index.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/containers/commandhistorylist.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/containers/commandinput.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/containers/commandline.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/containers/seedprompt.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/containers/walletpasswordprompt.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/constants/commandline.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/constants/helper.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/components/app.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/components/commandhistorylist.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/components/commandinput.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/components/commandline.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/components/seedprompt.js...
  Can't read file
Uploading file Sia-UI-v1.3.0-win32-x64/resources/app/plugins/Terminal/js/components/walletpasswordprompt.js...
```

**Comment by MeijeSibbel** [comment]
Not sure if it is important but sia-sync is also running and monitoring on the same folder.
