### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: storj-java.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform

### ISSUE THREAD

**Issue by AlexeyALeonov** [GooBox/goobox-sync-storj#70]
1. Installed a Java (i didn't have one) from the java.com
2. Extracted a zip into the folder and run goobox-sync-storj.bat
```
SLF4J: A number (1) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
Exception in thread "main" java.lang.UnsatisfiedLinkError: storj-java.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at io.storj.libstorj.Storj.loadLibrary(Storj.java:35)
        at io.storj.libstorj.Storj.<clinit>(Storj.java:27)
        at io.goobox.sync.storj.App.init(App.java:122)
        at io.goobox.sync.storj.App.main(App.java:52)
```

However, my Windows 10 is 64 bit

**Comment by kaloyan-raev** [comment]
For some strange reason java.com suggests installing the 32-bit Java on 64-bit Windows. Thus the error you get.

You should uninstall this 32-bit Java and install 64-bit Java from here: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

The "Windows x64 Offline" one to be precise.

**Comment by MeijeSibbel** [comment]
This is because people use Google chrome to download JRE, google chrome is always installed as 32-bit and automated downloads will thus always download the 32-bit version.

**Comment by AlexeyALeonov** [comment]
Meije, Google Chrome have a only 64 bit version. The problem in www.java.com

**Comment by AlexeyALeonov** [comment]
Why your app can't use the Environment variables?
Such as STORJ_KEYPASS?

**Comment by kaloyan-raev** [comment]
Users are not supposed to use it as a console app. It's just the current state. There will be a GUI and we will figure out how to integrate the passcode there.
